export var qLine = {
	1: {
		title: "동아리에 신입으로 들어가서 아는 사람이 아무도 없는 상황",
		type: "EI",
		A: "어색한 건 못 참아 먼저 말 건다",
		B: "존버가 답이야.. <br>말 걸어주길 기다린다.",
		pro_num: "1/12",
	},
	2: {
		title: "드디어 과제 끝! 이제 뭐하지?",
		type: "EI",
		A: "바로 술 마시러 간다",
		B: "오늘은 하루 종일 못 봤던 드라마 <br>정주행이다",
		pro_num: "2/12",
	},
	3: {
		title: "소개팅을 나가서 이상형을 만난 당신",
		type: "EI",
		A: "주제를 던지면서 대화를 이끌어 나간다",
		B: "말을 많이 하기보다는 상대방의 <br>말을 들어준다",
		pro_num: "3/12",
	},
	4: {
		title: "소설을 끝까지 읽은 뒤 나는..",
		type: "SN",
		A: "아 다 읽었다",
		B: "주인공이 어떻게 살아갔을지<br>상상해본다",
		pro_num: "4/12",
	},
	5: {
		title: "일을 할 때 나는",
		type: "SN",
		A: "매뉴얼이 있는 편을 선호한다",
		B: "나만의 방식대로 매뉴얼을 만드는 걸 <br>선호한다",
		pro_num: "5/12",
	},
	6: {
		title: "술집 볼 때 1순위로 보는 요소는",
		type: "SN",
		A: "안주 퀄리티",
		B: "분위기",
		pro_num: "6/12",
	},
	7: {
		title: "친구와의 점심 약속 메뉴 결정은 어떻게?",
		type: "TF",
		A: "오늘은 이거 무조건 먹어야 돼.<br>메뉴는 내가 정한다",
		B: "뭐 먹어야 되지...?<br>친구에게 선택권을 넘긴다",
		pro_num: "7/12",
	},
	8: {
		title: "조원이 자료조사는 해왔으나 제대로 준비를 안한 것 같다",
		type: "TF",
		A: "여기 여기 다시 자료조사해서 <br>건네주세요",
		B: "그래도 하긴 했으니까... <br>내가 찾아서 보강하자",
		pro_num: "8/12",
	},
	9: {
		title: "친구의 이별 소식을 들은 당신",
		type: "TF",
		A: "왜 헤어졌어?",
		B: "말할 때까지 기다려준다",
		pro_num: "9/12",
	},
	10: {
		title: "시작도 안한 과제 마감일 3일 전 친구로부터 놀자는 전화에",
		type: "JP",
		A: "기다려봐 과제부터 먼저 끝내고",
		B: "내일의 나야 고생해라!<br> 오늘의 나는 일단 놀게",
		pro_num: "10/12",
	},
	11: {
		title: "수강신청 계획을 짜놓은 당신",
		type: "JP",
		A: "플랜 C까지 미리 계획해 놓았다",
		B: "플랜 C란 없다. <br>하나의 시간표만 짜놨다",
		pro_num: "11/12",
	},
	12: {
		title: "나는 평소에 시험공부를..",
		type: "JP",
		A: "미리미리 복습까지 해놓는다",
		B: "1주일 전부터 벼락치기!",
		pro_num: "12/12",
	},
};
export var result = {
	INFP: {
		animal: "'혼자 청춘드리마 찍는 중'",
		img_01: "./img/INFP.png",
		bar_img_01: "./img/bar_02.png",
		bar_img_02: "./img/bar_05.png",
		bar_img_03: "./img/bar_04.png",
		bar_img_04: "./img/bar_01.png",
		explain_02: [
			"학교 앞 분위기 좋은 곳은 모두 꿰차고 있음.",
			"공부하러 도서관 가놓고 폰만 만지다 옴.",
			"일벌리는 건 좋아하는데 마무리는 잘 못 지음.",
			"혼자 있는 걸 좋아하면서도 한편으로 외로움. 그렇다고 밖에 나가긴 싫음.",
			"감수성이 풍부해서 망상 놀이를 자주 함.",
			"가끔씩 강의를 듣다 말고 창밖을 쳐다보며 감상에 빠짐.",
		],
		explain_ab: "동기여서 다행이다",
		img_aa: "./img/ESTJ.png",
		explain_bb: "인생 고민 하나도 없어 보임",
		img_ba: "./img/ESTP.png",
	},
	INFJ: {
		animal: "'개복치 인간 ver'",
		img_01: "./img/INFJ.png",
    	bar_img_01: "./img/bar_03.png",
		bar_img_02: "./img/bar_04.png",
		bar_img_03: "./img/bar_02.png",
		bar_img_04: "./img/bar_04.png",
		explain_02: [
            "내 사전에 실수란 없음, 그래서 팀플 할 때 스트레스를 많이 받음.",
            "걱정이 심하게 많아서 혼자 시뮬레이션 돌려보고 혼자 우울해함.",
            "팀플할 때 한 명이 손해봐야 되는 상황이면 그냥 본인이 희생함.",
            "말은 안 하지만 속으로는 누구보다 빠르게 남들과는 다르게 상대방 장단점 파악 중임.",
            "주변 사람들 성격에 따라 내 성격도 바뀜."
        ],
		explain_ab: "인생 고민 하나도 없어 보임",
		img_aa: "./img/ESTP.png",
		explain_bb: "동기여서 다행이다",
		img_ba: "./img/ESTJ.png",
	},
	INTP: {
		animal: "'나무늘보가 부러워'",
		img_01: "./img/INTP.png",
        
		bar_img_01: "./img/bar_05.png",
		bar_img_02: "./img/bar_04.png",
		bar_img_03: "./img/bar_02.png",
		bar_img_04: "./img/bar_01.png",
		explain_02: [
            "침대하고 물아일체 되는 게 인생의 낙임.",
            "뭐만 물어보면 일단 가능하다고 뱉고 봄. 근자감이 넘침.",
            "규칙을 극도로 싫어함.",
            "과 생활, 동아리 생활해야 할 이유를 못 느낌. ",
            "남들처럼 평범히 사는건 싫음.",
		    "친구들 자취방 데려오면 자취방 클라스보고 지렸다 함."
        ],
		explain_ab: "판도라의 상자",
		img_aa: "./img/ESFJ.png",
		explain_bb: "노는게 제일 좋은 뽀로로",
		img_ba: "./img/ESFP.png",
	},
	INTJ: {
		animal: "'혼자서도 잘 하는 척척박사'",
		img_01: "./img/INTJ.png",
		
		bar_img_01: "./img/bar_04.png",
		bar_img_02: "./img/bar_03.png",
		bar_img_03: "./img/bar_01.png",
		bar_img_04: "./img/bar_03.png",
        explain_02: [
            "과제하다 문제가 생기면 물어보기보다는 도서관 가서 책을 한 권 더 읽어봄.",
            "말수는 적지만 할 말은 다 함.",
            "일을 남들보다 빨리 배워서 선배들에게 이쁨 받음.",
            "제일 싫어하는 부류는 팀플같이할 때 실력 없는 사람들.",
            "무표정인데 화났냐는 소리를 자주 들음.",
            "직업 뭐가 어울릴 거 같냐고 친구들한테 물어보면 10중 9는 연구원이라고 함."
        ],
		explain_ab: "노는게 제일 좋은 뽀로로",
		img_aa: "./img/ESFP.png",
		explain_bb: "판도라의 상자",
		img_ba: "./img/ESFJ.png",
	},
	ISFP: {
		animal: "'알아서 해주길 바라는 결정장애'",
		img_01: "./img/ISFP.png",
		
		bar_img_01: "./img/bar_02.png",
		bar_img_02: "./img/bar_02.png",
		bar_img_03: "./img/bar_03.png",
		bar_img_04: "./img/bar_03.png",
        explain_02: [
            "얼굴에 감정이 다 드러남.",
            "선택장애가 심해서 다 양보함.",
            "점심메뉴, 안주 다 양보하고 팀플 역할도 다 양보해서 결국 남는 거 맡음.",
            "그러다 가끔씩 결단력 생기면 무조건 그거 해야 함.",
            "노는 게 싫은 건 아닌데 약속 파토 나길 바람.",
            "무리 내에게 노래 잘 부르는 친구 역할을 담당하고 있음."
        ],
		explain_ab: "반장 많이 해봤을거 같음",
		img_aa: "./img/ENTJ.png",
		explain_bb: "눈 마주치면 한 대 칠거 같음",
		img_ba: "./img/ENTP.png",
	},
	ISFJ: {
		animal: "'지켜줘야 할 것 같은 강아지형'",
		img_01: "./img/ISFJ.png",
		
		bar_img_01: "./img/bar_02.png",
		bar_img_02: "./img/bar_04.png",
		bar_img_03: "./img/bar_04.png",
		bar_img_04: "./img/bar_02.png",
        explain_02: [
            "팀플 자료조사 역할 맡으려고 맨날 가위바위보 해야 됨.",
            "친구들이랑 있으면 말 많은데 안 친한 사람들이랑 있으면 입꾹닫 시전함.",
            "다른 사람들 눈치를 많이 봐서 착한 사람으로 남고 싶어 함. ",
            "널고 얕게보다는 깊고 좁게.",
            "사람들하고 친해지는 데 시간이 걸려서 새 학기 때마다 외로움.",
            "누가 나보고 뭐라 하면 최대한 고치려고 함.",
		    "자기에 대한 확신이 없어서 남한테 내 가치를 인정받으려고 함."
        ],
		explain_ab: "눈 마주치면 한 대 칠거 같음",
		img_aa: "./img/ENTP.png",
		explain_bb: "반장 많이 해봤을거 같음",
		img_ba: "./img/ENTJ.png",
	},
	ISTP: {
		animal: "'혼자서도 잘 놀아요'",
		img_01: "./img/ISTP.png",
		
		bar_img_01: "./img/bar_05.png",
		bar_img_02: "./img/bar_01.png",
		bar_img_03: "./img/bar_02.png",
		bar_img_04: "./img/bar_02.png",
        explain_02: [
            "개인주의 성향이 강해서 팀플 있는 강의를 극혐함.",
            "팀플 있는 경우 피해 받은 거 싫어해서 선 넘으려고 하면 칼같이 쳐냄.",
            "운동 동아리에서 활동 중이거나 함교 앞 체육관에 다니고 있음.",
            "특정 분야에만 능력치 몰빵임.",
            "대화하다가도 할 말 없으면 그냥 말 안 함.",
            "연락 자체도 귀찮아해서 종강하면 개강할 때까지 먼저 연락 안 함.",
            "'옷 잘 입는 애' 축에 속함.",
            "효율성이 무엇보다 중요함. 어딜 가던 항상 최단 루트 계산해냄."
        ],
		explain_ab: "나를 따르라!<br> 종교지도자 꿈나무",
		img_aa: "./img/ENFJ.png",
		explain_bb: "뇌에서 필터 안 거치고<br> 일단 뱉고봄",
		img_ba: "./img/ENFP.png",
	},
	ISTJ: {
		animal: "'계획 짜는 일은 다 내꺼임'",
		img_01: "./img/ISTJ.png",
		
		bar_img_01: "./img/bar_03.png",
		bar_img_02: "./img/bar_01.png",
		bar_img_03: "./img/bar_02.png",
		bar_img_04: "./img/bar_05.png",
        explain_02: [
			"완전 성실한 모범생. 과제는 공지 받는 즉시 계획을 짜서 착착 해나감.",
			"만나려면 며칠 전부터 약속 잡아야 됨 당일 약속 극혐해서 절대 안 나감.",
			"축제 때 몇 시까지 주점에서 놀고 언제부터 자리 맡아놓을지 언제 술집 갈지 머리속으로 다 생각해 놓음.",
			"익숙한 게 최고이기 때문에 항상 가던 술집, 밥집만 가서 단골 가게가 몇 군데 있음.",
			"동아리나 과 내에서 임원 자리를 맡으려고 하지는 않지만 막상 맡으면 책임감 때문에 잘함.",
		    "모르는거 생기면 선배한테 물어보면 됐던 새내기 때가 그리움."
        ],
		explain_ab: "뇌에서 필터 안 거치고<br> 일단 뱉고봄",
		img_aa: "./img/ENFP.png",
		explain_bb: "나를 따르라!<br> 종교지도자 꿈나무",
		img_ba: "./img/ENFJ.png",
	},
	ENFP: {
		animal: "'뇌에서 필터 안 거치고 일단 뱉고 봄'",
		img_01: "./img/ENFP.png",
		
		bar_img_01: "./img/bar_02.png",
		bar_img_02: "./img/bar_03.png",
		bar_img_03: "./img/bar_04.png",
		bar_img_04: "./img/bar_00.png",
        explain_02: [
            "엠티 갈 때 장보는 거에서 배제됨.(뜬금없이 옥수수콘 사자하고 그럼)",
            "어딜 가던 분위기 메이커임.",
            "선후배, 너나 할거 없이 모든 사람이 좋아함.",
            "시험기간에 공부하겠답시고 도서관 가지만 30분 공부하고 3시간 떠들다 집 옴.",
            "팀플 할 때 떠오르는 거 있으면 일단 내뱉고 봄. 아이디어뱅크마냥 쭉쭉 나옴. 근데 99%는 조원들한테 컷당함.",
            "대체로 밝은 편인데 속으로는 우울한 면도 있음."
        ],
		explain_ab: "계획 짜는 일은 다 내거임",
		img_aa: "./img/ISTJ.png",
		explain_bb: "혼자서도 잘 놀아요",
		img_ba: "./img/ISTP.png",
	},
	ENFJ: {
		animal: "'나를 따르라! 종교지도자 꿈나무'",
		img_01: "./img/ENFJ.png",
		
		bar_img_01: "./img/bar_01.png",
		bar_img_02: "./img/bar_02.png",
		bar_img_03: "./img/bar_04.png",
		bar_img_04: "./img/bar_04.png",
        explain_02: [
            "호불호 안 갈리는 인싸.",
            "섬세하고 사려 깊어서 남들의 관심사를 잘 파악함.",
            "남들이 어려워하는 사람하고도 잘 지냄.",
            "직업으로 선생님, 종교가 생각해본 적 있음.",
            "사진 찍거나 글 쓰는 걸 좋아함.",
            "그래서 기념일에 편지 챙겨주는 거 좋아함.",
            "조장 맡는 거 좋아함.",
            "목표를 항상 이상적인 것과 연결 지음."
        ],
		explain_ab: "혼자서도 잘 놀아요",
		img_aa: "./img/ISTP.png",
		explain_bb: "계획 짜는 일은 다 내거임",
		img_ba: "./img/ISTJ.png",
	},
	ENTP: {
		animal: "'눈 마주치면 한 대 칠 거 같음'",
		img_01: "./img/ENTP.png",
		
		bar_img_01: "./img/bar_02.png",
		bar_img_02: "./img/bar_01.png",
		bar_img_03: "./img/bar_00.png",
		bar_img_04: "./img/bar_01.png",
        explain_02: [
            "남들이 발견하지 못했던 문제점을 잘 찾아냄.",
            "스스로를 엄청 믿어서 항상 확신에 차있음.",
            "그래서 내가 틀린 게 아니라 세상이 틀린 거라면서 세상하고 싸우려고 함.",
            "관습보다는 자기 주관이 더 중요해서 주변에 적이 많은 스타일. 그러나 전혀 개의치 않음.",
            "기세다는 소리 맨날 들음. ",
		    "불합리한 거 못 참음."
        ],
		explain_ab: "지켜줘야 할 것 같은<br> 강아지형",
		img_aa: "./img/ISFJ.png",
		explain_bb: "알아서 해주길 바라는<br> 결정장애",
		img_ba: "./img/ISFP.png",
	},
	ENTJ: {
		animal: "'반장 많이 해봤을 거 같음'",
		img_01: "./img/ENTJ.png",

		bar_img_01: "./img/bar_01.png",
		bar_img_02: "./img/bar_03.png",
		bar_img_03: "./img/bar_01.png",
		bar_img_04: "./img/bar_05.png",
        explain_02: [
            "팀플 조장, 동아리 회장, 단과대 회장 등.. 리더 경험 최소 1회 있음.",
            "자기 목표에 방해되는 사람은 뒤도 안 돌아보고 선그음.",
            "일이 착착 진행될 때 쾌감을 느낌.",
            "사람들을 잘 이끌긴 하지만 독선적인 면 때문에 뒤에서 욕먹기도 함.",
		    "일은 전략적, 계획적으로 해야 된다고 생각함."
        ],
		explain_ab: "알아서 해주길 바라는<br> 결정장애",
		img_aa: "./img/ISFP.png",
		explain_bb: "지켜줘야 할 것 같은<br> 강아지형",
		img_ba: "./img/ISFJ.png",
	},
	ESFP: {
		animal: "'노는 게 제일 좋은 뽀로로'",
		img_01: "./img/ESFP.png",
		
		bar_img_01: "./img/bar_00.png",
		bar_img_02: "./img/bar_01.png",
		bar_img_03: "./img/bar_04.png",
		bar_img_04: "./img/bar_00.png",
        explain_02: [
            "공부하러 대학교 온 게 아니라 사실 놀러 왔음.",
            "공부하러 도서관 가놓고 폰만 만지다 옴.",
            "다른 사람 생일도 자기 생일처럼 좋아함. 깜짝 이벤트를 할 수 있기 때문임.",
            "어색함이란 내 사전에 없음. 어제 처음 만난 사람도 다음날이면 짱친임.",
            "시험은 미루고 미루다가 벼락치기함.",
            "돈 쓴 기억은 없는데 통장 잔고는 맨날 텅 비어있음.",
            "자기 얘기하는 거 좋아해서 주변 사람들이 내 비밀 다 알고 있음.",
		    "술자리에서 진지한 얘기 나오는 거 못 견딤."
        ],
		explain_ab: "혼자서도 잘 하는 척척박사",
		img_aa: "./img/INTJ.png",
		explain_bb: "나무늘보가 부러워",
		img_ba: "./img/INTP.png",
	},
	ESFJ: {
		animal: "'판도라의 상자'",
		img_01: "./img/ESFJ.png",

		bar_img_01: "./img/bar_00.png",
		bar_img_02: "./img/bar_01.png",
		bar_img_03: "./img/bar_05.png",
		bar_img_04: "./img/bar_04.png",
        explain_02:[
            "인싸 그 자체임 선후배, 동기들이 내 이름은 다 앎.",
            "분명 과제 이야기하려고 모였는데 과제는 뒷전이고 일단 자기소개부터 하자고 함.",
            "별거 아닌 이야기에도 크게 웃어주는 리액션 맛집임.",
            "그래서 의도치 않게 판도라 상자의 역할을 맡음. 내가 입 여는 날은 누구 한 명 골로 가는 날임.",
		    "웃으면서 팩폭 날리는 거 잘함."
        ],
		explain_ab: "나무늘보가 부러워",
		img_aa: "./img/INTP.png",
		explain_bb: "혼자서도 잘 하는 척척박사",
		img_ba: "./img/INTJ.png",
	},
	ESTP: {
		animal: "'인생 고민 하나도 없어 보임'",
		img_01: "./img/ESTP.png",
		
		bar_img_01: "./img/bar_01.png",
		bar_img_02: "./img/bar_01.png",
		bar_img_03: "./img/bar_02.png",
		bar_img_04: "./img/bar_01.png",
        explain_02: [ 
            "학교에서 1분에 한 명꼴로 아는 사람 마주침.",
            "하고 싶은 말 다 하고 자존감이 높아서 딱히 스트레스가 없음.",
            "명령 받는 걸 싫어하고 주관이 뚜렷함.",
            "발표 들을 때 잘 못 알아듣다가 마지막에 세줄 요약 나오면 그때 이해함.",
            "밥 먹고 집 가기로 하고 만났는데 술 마시고, 노래방가고 머릿속에 떠오르는 거 다 하고 헤어짐.",
            "직설적이라 안친한 사람들에게 욕먹을 때가 많음."
        ],
		explain_ab: "개복치 인간 ver",
		img_aa: "./img/INFJ.png",
		explain_bb: "혼자서 청춘드리마 찍는 중",
		img_ba: "./img/INFP.png",
	},
	ESTJ: {
		animal: "'동기여서 다행이다'",
		img_01: "./img/ESTJ.png",
		bar_img_01: "./img/bar_01.png",
		bar_img_02: "./img/bar_01.png",
		bar_img_03: "./img/bar_00.png",
		bar_img_04: "./img/bar_05.png",
		explain_02: [
            "관종끼 있어서 팀플 역할은 무조건 발표 맡으려고 함.",
            "항상 주도해서 본인이 원하는 방향으로 이끌어 내야 적성이 풀림.",
            "사실 그냥 혼자 다 맡아서 하는 게 더 편함.",
            "계획적으로 움직임.",
            "옷 사지도 않을 건데 옷 사러 가고 이런 거 안 함. 남을 위해 시간 쓰는 걸 싫어함.",
            "승부욕이 강해서 다른 사람보다 뒤처지면 부들부들함.",
            "아무리 친해도 일적으로 엮이면 같은 사람 맞나 싶음. 계획에 차질이 생기거나 불이익 당하면 불같이 화냄."
        ],
        explain_ab: "혼자서 청춘드리마 찍는 중",
		img_aa: "./img/INFP.png",
		explain_bb: "개복치 인간 ver",
		img_ba: "./img/INFJ.png",
	},
};


export var result02 = {
	INFP: {
		animal02: "'너 자신부터 알라'",
		img02_01: "./img/HINFP.png",
		bar_img02_01: "./img/redbar_02.png",
		bar_img02_02: "./img/redbar_05.png",
		bar_img02_03: "./img/redbar_04.png",
		bar_img02_04: "./img/redbar_01.png",
		explain02_02: [
            "공감능력 좋아보이지만 자기가 겪어본 일에 대해서만 공감능력 있음.",
            "고집 생기면 무조건 지 말이 법임.",    
            "자아성찰은 오지게 하는데 자기객관화는 항상 못 함.",
            "말 안 해도 자기가 원하는 걸 알아주길 바람.",
            "어쩌라는 건지 모르겠음."
        ],
        explain02_ab: "팀플할 때 그만좀 꺼드럭<br> 거렸으면",
		img02_aa: "./img/HESTJ.png",
		explain02_bb: "일찐놀이 중독<br> &nbsp",
		img02_ba: "./img/HESTP.png"
	},
	INFJ: {
		animal02: "'앞에선 웃고 뒤돌면 찌를 상'",
		img02_01: "./img/HINFJ.png",
		bar_img02_01: "./img/redbar_03.png",
		bar_img02_02: "./img/redbar_04.png",
		bar_img02_03: "./img/redbar_02.png",
		bar_img02_04: "./img/redbar_04.png",
		explain02_02: [
            "자상해보이지만 속으로는 항상 다른 생각 중임.",
            "혼자서 선 정하고 상대방이 넘으면 갑자기 손절침.",
            "속으로 사람 평가하고 기준에 따라 분류해서 안 맞으면 상대안함.",
            "직접 안 묻고 계속 은근슬쩍 떠보려고 함.",
            "사람 좋은 척 음흉한 흑막."
        ],
        explain02_ab: "일찐놀이 중독<br> &nbsp",
		img02_aa: "./img/HESTP.png",
		explain02_bb: "팀플할 때 그만좀 꺼드럭<br> 거렸으면",
		img02_ba: "./img/HESTJ.png"
	},
	INTP: {
		animal02: "'자가합리화 장인'",
		img02_01: "./img/HINTP.png",
		bar_img02_01: "./img/redbar_05.png",
		bar_img02_02: "./img/redbar_04.png",
		bar_img02_03: "./img/redbar_02.png",
		bar_img02_04: "./img/redbar_01.png",
		explain02_02: [
            "공능제임.",
            "소통할 줄 모르고 자기 의견 틀려도 '똥이 무서워서 피하냐 더러워서 피하지'라면서 합리화함.",
            "감정표현을 못 함.",
            "깨어있는 척 오지는 방구석 키보드워리어, 본인이 잠재적 천잰줄 아는데 사회성도 지능임.",
            "말할 때 요점을 못 잡고 중구난방식으로 말함."
        ],
        explain02_ab: "인맥으로 비리 저지를거<br> 같음",
		img02_aa: "./img/HESFJ.png",
		explain02_bb: "SNS는 인생의 낭비가 <br>딱 얘네 보고 말한 듯",
		img02_ba: "./img/HESFP.png"
	},
	INTJ: {
		animal02: "'무인도에서 혼자 사는 거 추천'",
		img02_01: "./img/HINTJ.png",
		bar_img02_01: "./img/redbar_04.png",
		bar_img02_02: "./img/redbar_03.png",
		bar_img02_03: "./img/redbar_01.png",
		bar_img02_04: "./img/redbar_03.png",
		explain02_02: [
            "남한테 의견 물어보긴 하는데 그냥 형식상 물어본거. 자기랑 의견 다르면 무시함.",
            "상대가 원하는 게 위로인지 해결책인지 구분 못 함.",
            "감정을 계산하려고 함.",
            "답답하거나, 타인은 이해하지 못 하는 자신만의 세계를 자랑스러워 하며 타인이 이해 못 하는 걸 확인하려고 함. 그거 확인받고 기분 좋아함.",
            "말뽄새부터 재수없음의 의인화. 그 누구도 이해 못 하는 블랙 유머 야심차게 던졌다가 묵음처리되는 포지션."
        ],
        explain02_ab: "SNS는 인생의 낭비가 <br>딱 얘네 보고 말한 듯",
		img02_aa: "./img/HESFP.png",
		explain02_bb: "인맥으로 비리 저지를거<br> 같음",
		img02_ba: "./img/HESFJ.png"
	},
	ISFP: {
		animal02: "'친구 앞에서만 방구석 여포'",
		img02_01: "./img/HISFP.png",
		bar_img02_01: "./img/redbar_02.png",
		bar_img02_02: "./img/redbar_02.png",
		bar_img02_03: "./img/redbar_03.png",
		bar_img02_04: "./img/redbar_03.png",
		explain02_02: [
            "바빠 보이지만 사실 하는 거 하나도 없음.",
            "하는 거 하나도 없으면서 가만히 앉아서 로또 당첨같은 거만 기대함.",
            "배려 잘하는 것 같지만 속으로는 하나부터 열까지 다 비판 중. 그래서 남은 객관적으로 잘 보는데 정작 본인은 객관적으로 못 봄.",
            "방구석 여포라는 단어가 딱 어울리는 유형",
            "예민하고 감수성 충만한 굼뱅이 얘네 절대 순한맛 아님 친해지면 팩폭 꽂고 난리남.",
        ],
        explain02_ab: "사람이 왜 이렇게 <br>못 됐어요..?",
		img02_aa: "./img/HENTJ.png",
		explain02_bb: "얕은 지식으로 깝치는 <br>아가리 파이터",
		img02_ba: "./img/HENTP.png"
	},
	ISFJ: {
		animal02: "'뒷담화 할 때만 줏대생김'",
		img02_01: "./img/HISFJ.png",
		bar_img02_01: "./img/redbar_02.png",
		bar_img02_02: "./img/redbar_04.png",
		bar_img02_03: "./img/redbar_04.png",
		bar_img02_04: "./img/redbar_02.png",
		explain02_02: [
            "소심하고 줏대 하나도 없음.",
            "배려심있고 예의있어 보이지만 본성은 개깐깐한데 참고 있는거",
            "눈 밖에 나면 싫어할 이유를 찾아서라도 싫어해 함.",
            "뒷담화의 늪에 바진 줏대없는 갈대",
            "본인이 착해서 참는다고 생각하는데 사실 남들이 나를 바라보는 시선을 신경써서 그런거임."
        ],
        explain02_ab: "얕은 지식으로 깝치는 <br>아가리 파이터",
		img02_aa: "./img/HENTP.png",
		explain02_bb: "사람이 왜 이렇게 <br>못 됐어요..?",
		img02_ba: "./img/HENTJ.png"
	},
	ISTP: {
		animal02: "'입에청테이프 붙여야함'",
		img02_01: "./img/HISTP.png",
		bar_img02_01: "./img/redbar_05.png",
		bar_img02_02: "./img/redbar_01.png",
		bar_img02_03: "./img/redbar_02.png",
		bar_img02_04: "./img/redbar_02.png",
		explain02_02: [
            "배려심이 뭔지 모름.",
            "자기 할 말 하는데 급해서 남이 말하는 거 못 견딤.",
            "그 와중에 솔직해서 선의의 거짓말 같은거 안해 상대방을 빡치게 함.",
            "근데 자기가 상처받거나 손해 보면 난리침.",
            "충고를 해도 잘 안 받아들임."    
        ],
        explain02_ab: "꼬봉도 아니고 맨날지 <br>감정에 맞춰주길 바람",
		img02_aa: "./img/HENFJ.png",
		explain02_bb: "나이는 20대인데 <br>정신연령은 초딩보다 못 함",
		img02_ba: "./img/HENFP.png"
	},
	ISTJ: {
		animal02: "'시대 흐름에 뒤쳐지는 1순위'",
		img02_01: "./img/HISTJ.png",
		bar_img02_01: "./img/redbar_03.png",
		bar_img02_02: "./img/redbar_01.png",
		bar_img02_03: "./img/redbar_02.png",
		bar_img02_04: "./img/redbar_05.png",
		explain02_02: [
            "융통성 하나도 없는데 자기는 융통성 있고 객관적이라고 생각함.",
            "한 번 배운 체계 속에서 못 벗어남. 그래서 새로운 논리를 받아들이지 못 함.",
            "개노잼이라는 소리 자주 들음.",
            "자기 객관화를 잘 못해서 MBTI테스트하면 INTJ 나올 때도 있음."      
        ],
        explain02_ab: "나이는 20대인데 <br>정신연령은 초딩보다 못 함",
		img02_aa: "./img/HENFP.png",
		explain02_bb: "꼬봉도 아니고 맨날지 <br>감정에 맞춰주길 바람",
		img02_ba: "./img/HENFJ.png"
	},
	ENFP: {
		animal02: "'나이는 20대인데 정신연령은 초딩보다 못 함'",
		img02_01: "./img/HENFP.png",
		bar_img02_01: "./img/redbar_02.png",
		bar_img02_02: "./img/redbar_03.png",
		bar_img02_03: "./img/redbar_04.png",
		bar_img02_04: "./img/bar_00.png",
		explain02_02: [
            "애새키같다는 말을 자주 들음.",
            "근데 스스로는 자기는 성숙하고 어두운 면이 있다고 생각함. 남이 보면 걍 딱 중2병임.",
            "기분나쁘면 못 알아들은 척, 모르는 척 하는데 다 티남.",
            "멘탈 개약해서 잘 삐지고 빼애액대기 장인임.",
            "놀이동산 평생 이용권 끊어주고 솜사탕까지 쥐어줘야 만족할 듯."
            ],
        explain02_ab: "시대 흐름에 뒤처지는 1순위",
		img02_aa: "./img/HISTJ.png",
		explain02_bb: "입에 청테이프 붙여야 됨",
		img02_ba: "./img/HISTP.png"
	},
	ENFJ: {
		animal02: "'꼬봉도 아니고<br>맨날 지 감정에 맞춰주길 바람'",
		img02_01: "./img/HENFJ.png",
		bar_img02_01: "./img/redbar_01.png",
		bar_img02_02: "./img/redbar_02.png",
		bar_img02_03: "./img/redbar_04.png",
		bar_img02_04: "./img/redbar_04.png",
		explain02_02: [
            "감정적이라 지 기분 안 좋으면 주변 사람한테 괜히 난리침.",
            "그리고 주변 사람한테 난리친 거 후회화면서 또 지 혼자 우울해 함.",
            "사람들한테 다정한 편이지만 한 번 눈 밖에 나면 답 없음.",
            "정 때문에 일을 그르칠 때가 있음.",
            "감정에 휘둘려서 객관적으로 판단을 못 하기 때문임.",
            "퍼주기만 하고 자기 몫을 못 챙김."
        ],
        explain02_ab: "입에 청테이프 붙여야 됨",
		img02_aa: "./img/HISTP.png",
		explain02_bb: "시대 흐름에 뒤처지는 1순위",
		img02_ba: "./img/HISTJ.png"
	},
	ENTP: {
		animal02: "'얕은 지식으로 깝치는 아가리 파이터'",
		img02_01: "./img/HENTP.png",
		bar_img02_01: "./img/redbar_02.png",
		bar_img02_02: "./img/redbar_01.png",
		bar_img02_03: "./img/bar_00.png",
		bar_img02_04: "./img/redbar_01.png",
		explain02_02: [
            "빈 수레가 요란하다는 말이 딱 어울림.",
            "시비터는 거 좋아하는 아가리 파이터인데 제대로 아는 건 얼마 없음. 그래서 상대방이 팩트로 털면 역관광 당함.",
            "자기 말빨과 재치를 너무 믿음. 지가 제일 똑똑한 줄 앎",
            "ㅂㄷㅂㄷ대는거 다 보이는데 혼자 쿨한척 함."    
        ],
        explain02_ab: "뒷담화 할 때만 줏대생김",
		img02_aa: "./img/HISFJ.png",
		explain02_bb: "친구 앞에서만 방구석 여포",
		img02_ba: "./img/HISFP.png"
	},
	ENTJ: {
		animal02: "'사람이 왜 이렇게 못 됐어요..?'",
		img02_01: "./img/HENTJ.png",
		bar_img02_01: "./img/redbar_01.png",
		bar_img02_02: "./img/redbar_03.png",
		bar_img02_03: "./img/redbar_01.png",
		bar_img02_04: "./img/redbar_05.png",
		explain02_02: [
            "평소엔 논리가 중요하다면서 지가 지적당하면 논리 개나줘버리고 부들댐.",
            "뭐가 그리 잘났는지 모르겠는데 거만의 황제임.",
            "다른 사람 일부로 물 맥이고 상쳐주는 경우 많음. 상처 받아도 싸다고 생각하기 때문.",
            "소시오패스 거진 타노스급."
        ],
        explain02_ab: "친구 앞에서만 방구석 여포",
		img02_aa: "./img/HISFP.png",
		explain02_bb: "뒷담화 할 때만 줏대생김",
		img02_ba: "./img/HISFJ.png"
	},
	ESFP: {
		animal02: "'SNS는 인생의 낭비가 딱 <br>얘네 보고 말한 듯'",
		img02_01: "./img/HESFP.png",
		bar_img02_01: "./img/bar_00.png",
		bar_img02_02: "./img/redbar_01.png",
		bar_img02_03: "./img/redbar_04.png",
		bar_img02_04: "./img/bar_00.png",
		explain02_02: [
            "SNS만 중독이면 다행일정도로 개관종.",
            "유행에 동반하지 못 하면 못 견딤.",
            "꿈은 맨날 꾸는데 똑바로 한 적은 한 번도 없음.",
            "내 인기가 제일 중요함.",
            "타인 평가는 잘하면서 자기가 평가 당하는 건 못 견딤."
        ],
        explain02_ab: "무인도에서 혼자 사는 거 추천",
		img02_aa: "./img/HINTJ.png",
		explain02_bb: "자기합리화 장인",
		img02_ba: "./img/HINTP.png"
	},
	ESFJ: {
		animal02: "'인맥으로 비리 저지를거 같음'",
		img02_01: "./img/HESFJ.png",
		bar_img02_01: "./img/bar_00.png",
		bar_img02_02: "./img/redbar_01.png",
		bar_img02_03: "./img/redbar_05.png",
		bar_img02_04: "./img/redbar_04.png",
		explain02_02: [
            "외로움을 못 견딤. 이 정도면 타인의 존증.",
            "능력도 없으면서 인맥으로 커버치는 경우가 종종 있음.",
            "다른 사람이 자기한테 뭐 안 털어 놓으면 혼자 서운해하면서 친목질 강요함.",
            "남들이 너무 신경써서 뒷담화 제조기임.",
            "악덕 부녀회장 상대가 거절하는데 모임 때마다 자꾸 입안에 뭐 쑤셔넣는 포지션. 이때 반응 별로면 왁왁거리는데 개피곤함 무조건 유딩마냥 빵긋 웃어줘야됨."    
        ],
        explain02_ab: "자기합리화 장인",
		img02_aa: "./img/HINTP.png",
		explain02_bb: "무인도에서 혼자 사는 거 추천",
		img02_ba: "./img/HINTJ.png"
	},
	ESTP: {
		animal02: "'일찐놀이 중독'",
		img02_01: "./img/HESTP.png",
		bar_img02_01: "./img/redbar_01.png",
		bar_img02_02: "./img/redbar_01.png",
		bar_img02_03: "./img/redbar_02.png",
		bar_img02_04: "./img/redbar_01.png",
		explain02_02: [
            "자기보다 약해보이면 그냥 무시함.",
            "남 생각 안하고 말 싸가지 없게 잘 내뱉음.",
            "지 맘에 안들면 싸우려고 함.",
            "사회적인 척 하다가 갑자기 쎄한 행동 함.",
            "술마실 때마다 시비 털거나 걸리기 딱 좋은 유형."    
        ],
        explain02_ab: "앞에선 웃고 뒤돌면 찌를 상",
		img02_aa: "./img/HINFJ.png",
		explain02_bb: "너 자신부터 알라",
		img02_ba: "./img/HINFP.png"
	},
	ESTJ: {
		animal02: "'팀플할 때 그만좀 꺼드럭 거렸으면'",
		img02_01: "./img/HESTJ.png",
		bar_img02_01: "./img/redbar_01.png",
		bar_img02_02: "./img/redbar_01.png",
		bar_img02_03: "./img/bar_00.png",
		bar_img02_04: "./img/redbar_05.png",
		explain02_02: [
            "지가 무조건 맞다고 생각함.",
            "전형적인 강약약강. 윗사람한테는 싸바싸바 장난 아님.",
            "꼰대 최종보스",
            "지 뜻대로 주도 안 되면 욕 박고 탈주함.",
            "근데 스스로 자기는 유능하다고 나름 따뜻한 사람이라고 착각함."
        ],
        explain02_ab: "너 자신부터 알라",
		img02_aa: "./img/HINFP.png",
		explain02_bb: "앞에선 웃고 뒤돌면 찌를 상",
		img02_ba: "./img/HINFJ.png"
	},
};